use_frameworks!

platform :ios, '9.0'

target 'FYFPlugins_Example' do
  pod 'FYFPlugins', :path => '../'
  
  target 'FYFPlugins_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
